Repository p2hacks/teamR01, pull requests merged in 2019-12, with the labels that each got.

#7 update README.md
  README.md
Labels: enhancement

#8 add noma information
  README.md
Labels: documentation, enhancement, good first issue

#9 update README 目標 itou
  README.md
Labels: documentation, enhancement, good first issue

#10 edit on branch readme85
  README.md
Labels: documentation, enhancement, good first issue

#25 Create gitignore
  .gitignore
Labels: enhancement, good first issue

#30 Create server dir
  server/README.md
Labels: documentation, enhancement, good first issue

#32 create bff API model
  server/bff/Dockerfile
  server/bff/bff-api.js
  server/bff/package-lock.json
  server/bff/package.json
  server/bff/resolver/resolver.js
  server/bff/schema/schema.js
Labels: enhancement, good first issue

#27 create xcode projects
  Omamama/Omamama.xcodeproj/project.pbxproj
  Omamama/Omamama.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Omamama/Omamama.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Omamama/Omamama.xcodeproj/project.xcworkspace/xcuserdata/shotaro-yamada.xcuserdatad/UserInterfaceState.xcuserstate
  Omamama/Omamama.xcodeproj/xcuserdata/shotaro-yamada.xcuserdatad/xcschemes/xcschememanagement.plist
  Omamama/Omamama/AppDelegate.swift
  Omamama/Omamama/Assets.xcassets/AppIcon.appiconset/Contents.json
  Omamama/Omamama/Assets.xcassets/Contents.json
  Omamama/Omamama/Base.lproj/LaunchScreen.storyboard
  Omamama/Omamama/ContentView.swift
  Omamama/Omamama/Info.plist
  Omamama/Omamama/Preview Content/Preview Assets.xcassets/Contents.json
  Omamama/Omamama/SceneDelegate.swift
  Omamama/OmamamaTests/Info.plist
  Omamama/OmamamaTests/OmamamaTests.swift
  Omamama/OmamamaUITests/Info.plist
  Omamama/OmamamaUITests/OmamamaUITests.swift
Labels: enhancement, good first issue

#45 Create user api
  server/bff/bff-api.js
  server/bff/resolver/resolver.js
  server/bff/schema/schema.js
  server/docker-compose.yaml
  server/user/Dockerfile
  server/user/config/config.go
  server/user/controller/controller.go
  server/user/go.mod
  server/user/main.go
  server/user/model/model.go
  server/user/service/service.go
Labels: enhancement, good first issue

#43 アプリ起動時のスプラッシュ画面とアプリアイコンをつけました。
  Omamama/Omamama.xcodeproj/project.pbxproj
  Omamama/Omamama.xcodeproj/project.xcworkspace/xcuserdata/itoushingo.xcuserdatad/UserInterfaceState.xcuserstate
  Omamama/Omamama.xcodeproj/xcuserdata/itoushingo.xcuserdatad/xcschemes/xcschememanagement.plist
  Omamama/Omamama/Assets.xcassets/AppIcon.appiconset/Contents.json
  Omamama/Omamama/Assets.xcassets/AppIcon.appiconset/Frame 1icon.png
  Omamama/Omamama/Base.lproj/LaunchScreen.storyboard
Labels: good first issue

#50 Create present api
  server/bff/bff-api.js
  server/bff/resolver/resolver.js
  server/bff/schema/schema.js
  server/docker-compose.yaml
  server/present/Dockerfile
  server/present/config/config.go
  server/present/controller/controller.go
  server/present/go.mod
  server/present/main.go
  server/present/model/model.go
  server/rate/controller/controller.go
Labels: enhancement, good first issue

#48 Create send message api
  server/send-message/config/config.go
  server/send-message/controller/controller.go
  server/send-message/dbconnect/connect.go
  server/send-message/go.mod
  server/send-message/main.go
  server/send-message/model/model.go
Labels: enhancement

#53 Containerize send message api
  server/bff/bff-api.js
  server/bff/resolver/resolver.js
  server/bff/schema/schema.js
  server/docker-compose.yaml
  server/send-message/Dockerfile
  server/send-message/config/config.go
  server/send-message/controller/controller.go
  server/send-message/dbconnect/connect.go
  server/send-message/main.go
  server/send-message/model/model.go
Labels: enhancement, good first issue

#54 Add resources
  Omamama/Omamama.xcodeproj/project.pbxproj
  Omamama/Omamama.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Omamama/Omamama/SelectGift.storyboard
  Omamama/Resources copy/Frame 1icon.png
  Omamama/Resources copy/Sprash.jpeg
Labels: documentation, enhancement

#55 add screen and resources
  Omamama/Omamama.xcodeproj/project.xcworkspace/xcuserdata/naoki.xcuserdatad/UserInterfaceState.xcuserstate
  Omamama/Omamama.xcodeproj/xcuserdata/naoki.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Omamama/Omamama.xcodeproj/xcuserdata/naoki.xcuserdatad/xcschemes/xcschememanagement.plist
  Omamama/Omamama/Assets.xcassets/10000ratebutton.imageset/10000ratebutton.png
  Omamama/Omamama/Assets.xcassets/10000ratebutton.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/3000ratebutton.imageset/3000ratebutton.png
  Omamama/Omamama/Assets.xcassets/3000ratebutton.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/5000ratebutton.imageset/5000ratebutton.png
  Omamama/Omamama/Assets.xcassets/5000ratebutton.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/Frame 1icon.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/Frame 1icon.imageset/Frame 1icon.png
  Omamama/Omamama/Assets.xcassets/selectpresentbutton.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/selectpresentbutton.imageset/selectpresentbutton.png
  Omamama/Omamama/Assets.xcassets/userregistbutton_next.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/userregistbutton_next.imageset/userregistbutton_next.png
  Omamama/Omamama/Assets.xcassets/userregistbutton_regist.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/userregistbutton_regist.imageset/userregistbutton_regist.png
  Omamama/Resources/10000ratebutton.png
  Omamama/Resources/3000ratebutton.png
  Omamama/Resources/5000ratebutton.png
  Omamama/Resources/selectpresentbutton.png
  Omamama/Resources/userregistbutton_next.png
  Omamama/Resources/userregistbutton_regist.png
Labels: enhancement

#57 add selectgiftpage
  Omamama/Omamama/SelectGiftViewController.swift
Labels: enhancement

#58 Create pair api
  .gitignore
  server/bff/bff-api.js
  server/bff/resolver/resolver.js
  server/bff/schema/schema.js
  server/docker-compose.yaml
Labels: enhancement, good first issue

#59 Add pair api
  .gitignore
  server/pair/Dockerfile
  server/pair/config/config.go
  server/pair/controller/controller.go
  server/pair/go.mod
  server/pair/main.go
  server/pair/model/model.go
Labels: enhancement, good first issue

#64 Add send present page
  Omamama/Omamama.xcodeproj/project.pbxproj
  Omamama/Omamama.xcodeproj/project.xcworkspace/xcuserdata/naoki.xcuserdatad/UserInterfaceState.xcuserstate
  Omamama/Omamama/Assets.xcassets/sendpresentbutton.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/sendpresentbutton.imageset/sendpresentbutton.png
  Omamama/Omamama/Assets.xcassets/決済通知.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/決済通知.imageset/決済通知.png
  Omamama/Omamama/SelectGift.storyboard
  Omamama/Omamama/SelectGiftViewController.swift
  Omamama/Omamama/SendGift/SendGift.storyboard
  Omamama/Omamama/SendGift/SendGiftViewController.swift
  Omamama/Omamama/userRegistrationPage.swift
Labels: enhancement

#65 create selectratepage
  Omamama/Omamama/SelectRate.storyboard
  Omamama/Omamama/SelectRateViewController.swift
Labels: enhancement

#67 Create card info api
  server/bff/bff-api.js
  server/bff/resolver/resolver.js
  server/bff/schema/schema.js
  server/card-info/Dockerfile
  server/card-info/config/config.go
  server/card-info/controller/controller.go
  server/card-info/go.mod
  server/card-info/main.go
  server/card-info/model/model.go
  server/docker-compose.yaml
Labels: enhancement, good first issue

#66 install apollo with pod
  Omamama/Omamama/SelectGift.storyboard
  Omamama/Omamama/SelectGiftViewController.swift
  Omamama/Omamama/SelectRate.storyboard
  Omamama/Omamama/SelectRateViewController.swift
  Omamama/Omamama/SendGift/SendGift.storyboard
  Omamama/Omamama/SendGift/SendGiftViewController.swift
Labels: enhancement

#68 Create get message api
  server/get-message/config/config.go
  server/get-message/controller/controller.go
  server/get-message/dbconnect/connect.go
  server/get-message/go.mod
  server/get-message/main.go
  server/get-message/model/model.go
Labels: bug, enhancement

#72 Install cocoapods
  Omamama/Omamama/SendGift.storyboard
  Omamama/Omamama/SendGiftViewController.swift
Labels: bug

#74 Fix get message api
  server/bff/bff-api.js
  server/bff/resolver/resolver.js
  server/bff/schema/schema.js
  server/docker-compose.yaml
  server/get-message/Dockerfile
  server/get-message/config/config.go
  server/get-message/controller/controller.go
  server/get-message/main.go
  server/get-message/model/model.go
Labels: bug, enhancement, good first issue

#76 Apply apollo ios
  Omamama/Omamama/schema.json
  Omamama/Omamama/setUser.graphql
  Omamama/Omamama/setUser.swift
Labels: enhancement, good first issue

#81 Noma
  Omamama/Omamama/Assets.xcassets/logo.imageset/Contents.json
  Omamama/Omamama/Assets.xcassets/logo.imageset/logo.png
  Omamama/Omamama/Network.swift
  Omamama/Omamama/SceneDelegate.swift
  Omamama/Omamama/UserRegist_address.storyboard
  Omamama/Omamama/UserRegist_addressViewController.swift
  Omamama/Omamama/UserResist_card/UserRegist_card.storyboard
  Omamama/Omamama/UserResist_card/UserRegist_cardViewController.swift
  Omamama/Omamama/userRegistrationPage.swift
  README.md
Labels: documentation
